### ISSUE TITLE
SarConvert is not included in the latest release

### ISSUE THREAD

**Issue by NaiCha** [usagirei/PSO2_SymbolArt_ThumbnailHandler#2]
You forgot to include the SarConvert utility as part of the newest release. So people need to download both releases to get the latest updates as well as the SarConvert utility.

**Comment by usagirei** [comment]
Oops, there should be a new release up (v1.0.0.39 - ab1cefd)
, along with a new optional high-res rendering output for both the extension and SarConvert, i'll add some picture comparisons to the readme later
